### DISCUSSION TITLE
Build Multiple .torrent files in one time

### DISCUSSION THREAD

**Discussion by Genetik57** [AnimMouse/torrent-webseed-creator#4] [Ideas]
Hi,

This is possible to build for example 2, 3 or 4 different .torrent files in one time without having to modify the torrent.yml file 4 times to build 4 .torrent files?

I would like to put several different link to build several different .torrent file at once

Best regards

**Comment by AnimMouse** [comment]
```
name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name_1: "Firefox Setup 84.0"
  comment_1: "Firefox Setup 84.0"
  url_1: "https://cdn.stubdownloader.services.mozilla.com/builds/firefox-latest-ssl/en-US/win64/3fdd1318dfa06611263ee86c0c74dcd76fde4cf6763ea411e758b97a0578dee6/Firefox%20Setup%2084.0.exe"
  file_name_1: "Firefox Setup 84.0.exe"
  piece_size_1: 19 # Check the README.md for recommended piece size
  
  name_2: "Firefox Setup 84.0"
  comment_2: "Firefox Setup 84.0"
  url_2: "https://cdn.stubdownloader.services.mozilla.com/builds/firefox-latest-ssl/en-US/win64/3fdd1318dfa06611263ee86c0c74dcd76fde4cf6763ea411e758b97a0578dee6/Firefox%20Setup%2084.0.exe"
  file_name_2: "Firefox Setup 84.0.exe"
  piece_size_2: 19 # Check the README.md for recommended piece size
  
  name_3: "Firefox Setup 84.0"
  comment_3: "Firefox Setup 84.0"
  url_3: "https://cdn.stubdownloader.services.mozilla.com/builds/firefox-latest-ssl/en-US/win64/3fdd1318dfa06611263ee86c0c74dcd76fde4cf6763ea411e758b97a0578dee6/Firefox%20Setup%2084.0.exe"
  file_name_3: "Firefox Setup 84.0.exe"
  piece_size_3: 19 # Check the README.md for recommended piece size
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file 1
        run: wget -nv -O "$file_name_1" "$url_1"
        
      - name: Create torrent using mktorrent 1
        run: mktorrent -c "$comment_1" -l $piece_size_1 -o "${name_1}.torrent" -w "$url_1" "$file_name_1"
        
      - name: Delete file 1
        run: rm "$file_name_1"
        
      - name: Download file 2
        run: wget -nv -O "$file_name_2" "$url_2"
        
      - name: Create torrent using mktorrent 2
        run: mktorrent -c "$comment_2" -l $piece_size_2 -o "${name_2}.torrent" -w "$url_2" "$file_name_2"
        
      - name: Delete file 2
        run: rm "$file_name_2"
        
      - name: Download file 3
        run: wget -nv -O "$file_name_3" "$url_3"
        
      - name: Create torrent using mktorrent 3
        run: mktorrent -c "$comment_3" -l $piece_size_3 -o "${name_3}.torrent" -w "$url_3" "$file_name_3"
        
      - name: Delete file 3
        run: rm "$file_name_3"
        
      - name: Upload torrent file 1
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_1 }}
          path: ${{ env.name_1 }}.torrent
          
      - name: Upload torrent file 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_2 }}
          path: ${{ env.name_2 }}.torrent
          
      - name: Upload torrent file 3
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name_3 }}
          path: ${{ env.name_3 }}.torrent
```
