### ISSUE TITLE
Use workflow_dispatch inputs

### ISSUE THREAD

**Issue by AnimMouse** [AnimMouse/torrent-webseed-creator#12]
Instead of requiring to commit and push the parameters, use instead workflow_dispatch inputs to make it easy.

```
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
        
jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: wget ${{ github.event.inputs.url }}
```
